"""Build 035555.com static site: python3 _src/build.py  (writes HTML into the repo root)"""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from layout import page, DOMAIN, footer, modal
import pages_tools, pages_more, pages_guides

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
ALL = {**pages_tools.PAGES, **pages_more.PAGES, **pages_guides.PAGES}

BASE_FIX = ('<script>(function(){var p=location.pathname.split("/");var b=(location.hostname.endsWith("github.io")&&p[1])?"/"+p[1]+"/":"/";'
            'document.write(\'<base href="\'+b+\'">\')})();</script>')

for path, meta in ALL.items():
    depth = path.count("/")
    R = "../" * depth
    html = page(R, meta.get("current", path), meta["title"], meta["desc"], meta["body"](R), path,
                jsonld=meta.get("jsonld") or ({"@context": "https://schema.org", "@type": "Article", "headline": meta["title"].split(" | ")[0],
                                                "datePublished": "2026-09-28", "author": {"@type": "Organization", "name": "035555.com"},
                                                "publisher": {"@type": "Organization", "name": "035555.com"}} if meta.get("article") else None),
                og_type="article" if meta.get("article") else "website")
    if meta.get("abs_root"):
        html = html.replace('<meta charset="utf-8">', '<meta charset="utf-8">\n' + BASE_FIX, 1)
        html = html.replace('<link rel="canonical"', '<meta name="robots" content="noindex"><link rel="canonical"')
    dest = os.path.join(OUT, path)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "w", encoding="utf-8") as f:
        f.write(html)

# shared footer/modal injected by JS (keeps every page small)
import json as _json
_chunk = footer("%R%") + "\n" + modal("%R%")
open(os.path.join(OUT, "assets/js/layout.js"), "w", encoding="utf-8").write(
    "/* 035555.com shared footer, sticky CTA, cookie notice and lead modal. Generated by _src/build.py */\n"
    "(function(){var R=document.body.getAttribute('data-root')||'';document.body.insertAdjacentHTML('beforeend',"
    + _json.dumps(_chunk, ensure_ascii=False) + ".split('%R%').join(R));})();\n")

# sitemap
urls = [p for p in ALL if p != "404.html"]
sm = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
for p in urls:
    loc = DOMAIN + "/" + ("" if p == "index.html" else p)
    pr = "1.0" if p == "index.html" else ("0.9" if p in ("decoder.html", "lucky-number-checker.html", "dictionary.html", "leads.html") else "0.7")
    sm.append(f"  <url><loc>{loc}</loc><lastmod>2026-09-28</lastmod><priority>{pr}</priority></url>")
sm.append("</urlset>")
open(os.path.join(OUT, "sitemap.xml"), "w").write("\n".join(sm) + "\n")

static = {
    "robots.txt": f"User-agent: *\nAllow: /\n\nSitemap: {DOMAIN}/sitemap.xml\n",
    "ads.txt": "# Replace pub-XXXXXXXXXXXXXXXX with your AdSense publisher ID once approved:\n# google.com, pub-XXXXXXXXXXXXXXXX, DIRECT, f08c47fec0942fa0\n",
    ".nojekyll": "",
    "manifest.webmanifest": '{"name":"035555.com — Number Meanings","short_name":"035555","start_url":"./index.html","display":"standalone","background_color":"#fbf8f3","theme_color":"#c8102e","icons":[{"src":"assets/img/favicon.svg","sizes":"any","type":"image/svg+xml"}]}\n',
    "assets/img/favicon.svg": '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#c8102e"/><text x="32" y="42" font-family="Arial,Helvetica,sans-serif" font-size="28" font-weight="800" text-anchor="middle" fill="#fff">03</text></svg>\n',
}
for p, c in static.items():
    d = os.path.join(OUT, p); os.makedirs(os.path.dirname(d), exist_ok=True)
    open(d, "w", encoding="utf-8").write(c)
print("Built", len(ALL), "pages")
